create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  notes text default '',
  visits integer not null default 0,
  last_visit_label text default 'noua',
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  duration text not null,
  price integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  service text not null,
  appointment_date date not null default current_date,
  start_time time not null,
  duration text not null,
  price integer not null,
  status text not null default 'Noua',
  notes text default '',
  created_at timestamptz not null default now()
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date, start_time);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  expiration_time bigint,
  p256dh text not null,
  auth text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_notification_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.push_appointment_reminders (
  id bigint generated by default as identity primary key,
  reminder_key text not null unique,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.push_delivery_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  title text not null,
  body text not null default '',
  sent_count integer not null default 0,
  reminders_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists push_subscriptions_active_idx
  on public.push_subscriptions (active);

create index if not exists push_appointment_reminders_appointment_idx
  on public.push_appointment_reminders (appointment_id);

create index if not exists push_delivery_logs_created_idx
  on public.push_delivery_logs (created_at desc);

insert into public.services (name, duration, price, active)
select 'Natural volum (set nou)', '2h', 250, true
where not exists (select 1 from public.services where name = 'Natural volum (set nou)');

insert into public.services (name, duration, price, active)
select 'Natural  volum (întreținere)', '1h30 min', 220, true
where not exists (select 1 from public.services where name = 'Natural  volum (întreținere)');

insert into public.services (name, duration, price, active)
select 'Mega Volum (set nou)', '2h', 300, true
where not exists (select 1 from public.services where name = 'Mega Volum (set nou)');

insert into public.services (name, duration, price, active)
select 'Mega Volum (întreținere)', '2h', 250, true
where not exists (select 1 from public.services where name = 'Mega Volum (întreținere)');

insert into public.services (name, duration, price, active)
select 'Russian Volum (set nou)', '2h30min', 330, true
where not exists (select 1 from public.services where name = 'Russian Volum (set nou)');

insert into public.services (name, duration, price, active)
select 'Russian Volum (întreținere)', '2h', 280, true
where not exists (select 1 from public.services where name = 'Russian Volum (întreținere)');

insert into public.services (name, duration, price, active)
select 'Demontare extensii', '30min', 60, true
where not exists (select 1 from public.services where name = 'Demontare extensii');
