create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  notes text default '',
  visits integer not null default 0,
  last_visit_label text default 'noua',
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  service text not null,
  appointment_date date not null default current_date,
  start_time time not null,
  duration text not null,
  price integer not null,
  status text not null default 'Noua',
  created_at timestamptz not null default now()
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date, start_time);
