create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  notes text default '',
  visits integer not null default 0,
  last_visit_label text default 'noua',
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  duration text not null,
  price integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  service text not null,
  appointment_date date not null default current_date,
  start_time time not null,
  duration text not null,
  price integer not null,
  status text not null default 'Noua',
  notes text default '',
  created_at timestamptz not null default now()
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date, start_time);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  expiration_time bigint,
  p256dh text not null,
  auth text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_notification_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.push_appointment_reminders (
  id bigint generated by default as identity primary key,
  reminder_key text not null unique,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists push_subscriptions_active_idx
  on public.push_subscriptions (active);

create index if not exists push_appointment_reminders_appointment_idx
  on public.push_appointment_reminders (appointment_id);

insert into public.services (name, duration, price)
select 'Mega Volum', '3h', 350
where not exists (select 1 from public.services where name = 'Mega Volum');

insert into public.services (name, duration, price)
select 'Russian Volum', '2h 30m', 300
where not exists (select 1 from public.services where name = 'Russian Volum');

insert into public.services (name, duration, price)
select 'Intretinere', '2h', 220
where not exists (select 1 from public.services where name = 'Intretinere');
